### ISSUE TITLE
Inconsistent reporting

### ISSUE THREAD

**Issue by bbalansay** [todo-name/TODO-NAME#23]
If you make a report on one image, trying to report it again will give you the "Report submitted!" pop-up and not allow you to report it again. If you refresh the page, however, you can once again report the image. Not sure which one it is supposed to be, if either.

**Comment by lukepallen** [comment]
Symptom of larger issue of increased report handling requirement. Report handling will require a separate table for tracking user reports, similar to the user-likes table we had to add in as well. Additionally, this will prevent an issue where multiple user generated reports overwrite each other in content moderation. Unfortunately, due to the time precedent of creating and integrating a new table into the application set by the likedPosts table, this feature improvement will need to be postponed until the next full version release.
